### ISSUE TITLE
img_out: Tile error: User memory exceeded

### ISSUE THREAD

**Issue by meronmi** [kongdd/PML#2]
Dear Kong,
I am running your data_LAI_Whittaker.js in the play gorunf bu I get the following error:
img_out: Tile error: User memory exceeded
Am I doing something wrong?
Thanks and kind regards,
Michele

**Comment by kongdd** [comment]
The longest LAI input is about one year (92 images).  If more, it will be out of memory. Because GEE doesn't give enough memory.
By the way, you can have a try: (1) aggregate 4-day LAI into 8-day, then (2) smoothed by Whittaker

**Comment by kongdd** [comment]
Another option: 
uncomment in `exportTiles` https://github.com/kongdd/PML/blob/master/src/data_LAI_Whittaker.js#L107, which will split global into 10 tiles. Hence, only 1/10 memory used for each task.

**Comment by meronmi** [comment]
Dear Kong,
many thanks for your replay. FYI, I am using directly your script without modification (90 images) but I get the memory error anyhow. I am looking at it because I implemented for S2 and I get the same error also for very small areas (few pixels) and few images. Not sure what is going wrong.
Kind regards,
Michele

**Comment by kongdd** [comment]
I am not sure why. I succeed to smooth 4 years LAI inputs two years ago. But now only 1 year. The upper memory limit is smaller and smaller. I am also stuck at this problem for a long time.

You can post a question in the GEE developer forum.

**Comment by kongdd** [comment]
Hi @meronmi 
I tried to use Whittaker to smooth 2019 global MODIS LAI (500m, 4-day, about 90 images). It worked smoothly and produced the smoothed result after 10 hours. 
If the input LAI imgcol is in the 8-day scale, the script will be 4-times efficient.
